# Generated by Django 2.2.5 on 2022-05-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
